version: '3'

services:
  graphql-service:
    build: .
    depends_on: 
      - mongo
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9001:9000
    command: npm run dev

  mongo:
    image: mongo:3.4.23
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./datamongo:/data/db"